INSERT INTO pg_listings (
    pg_id,
    pg_name,
    locality,
    city,
    monthly_rent,
    sharing_type,
    gender,
    food_available,
    wifi,
    ac,
    laundry,
    security,
    distance_to_metro_km,
    rating
)
VALUES
(1, 'UrbanNest PG', 'Andheri East', 'Mumbai', 15000, 'Double', 'Female', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 0.80, 4.4),
(2, 'Comfort Stay', 'Andheri East', 'Mumbai', 12000, 'Triple', 'Female', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 1.20, 4.1),
(3, 'Metro Homes', 'Andheri West', 'Mumbai', 18000, 'Single', 'Female', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 0.50, 4.6),
(4, 'Green View PG', 'Andheri West', 'Mumbai', 13500, 'Double', 'Unisex', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 1.00, 4.2),
(5, 'Sunrise Residency', 'Powai', 'Mumbai', 16000, 'Double', 'Female', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 2.50, 4.5),
(6, 'LakeSide PG', 'Powai', 'Mumbai', 22000, 'Single', 'Unisex', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 1.80, 4.7),
(7, 'Budget Homes', 'Powai', 'Mumbai', 11000, 'Triple', 'Female', 'No', 'Yes', 'No', 'Yes', 'Yes', 3.20, 3.9),
(8, 'Elite Living', 'Bandra West', 'Mumbai', 25000, 'Single', 'Female', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 1.10, 4.8),
(9, 'Bandra Comfort', 'Bandra West', 'Mumbai', 19000, 'Double', 'Unisex', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 0.90, 4.5),
(10, 'City Girls PG', 'Bandra East', 'Mumbai', 14500, 'Double', 'Female', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 1.40, 4.2),
(11, 'Safe Haven', 'Goregaon East', 'Mumbai', 13000, 'Double', 'Female', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 0.70, 4.5),
(12, 'Home Away', 'Goregaon East', 'Mumbai', 10500, 'Triple', 'Female', 'Yes', 'Yes', 'No', 'No', 'Yes', 1.50, 4.0),
(13, 'Royal Residency', 'Goregaon East', 'Mumbai', 17500, 'Single', 'Unisex', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 0.60, 4.6),
(14, 'GreenNest', 'Goregaon West', 'Mumbai', 12500, 'Double', 'Female', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 1.00, 4.1),
(15, 'WorkLife PG', 'Malad West', 'Mumbai', 14000, 'Double', 'Female', 'No', 'Yes', 'No', 'Yes', 'Yes', 0.80, 4.4),
(16, 'Affordable Stay', 'Malad East', 'Mumbai', 10000, 'Triple', 'Unisex', 'No', 'Yes', 'No', 'Yes', 'Yes', 1.70, 3.8),
(17, 'Comfort Corner', 'Malad West', 'Mumbai', 15500, 'Double', 'Female', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 1.10, 4.3),
(18, 'Malad Heights', 'Malad West', 'Mumbai', 20000, 'Single', 'Unisex', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 0.90, 4.6),
(19, 'Chembur Comfort', 'Chembur', 'Mumbai', 12000, 'Double', 'Female', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 0.70, 4.2),
(20, 'Metro View PG', 'Chembur', 'Mumbai', 15000, 'Double', 'Unisex', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 0.40, 4.5),
(21, 'Budget Nest', 'Chembur', 'Mumbai', 9000, 'Triple', 'Female', 'No', 'Yes', 'No', 'No', 'Yes', 1.60, 3.7),
(22, 'Harbour Homes', 'Vashi', 'Mumbai', 11000, 'Double', 'Female', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 0.90, 4.1),
(23, 'Vashi Residency', 'Vashi', 'Mumbai', 14500, 'Single', 'Unisex', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 0.50, 4.5),
(24, 'Navi Comfort', 'Nerul', 'Mumbai', 10000, 'Double', 'Female', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 0.80, 4.0),
(25, 'Palm Residency', 'Nerul', 'Mumbai', 13500, 'Single', 'Unisex', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 0.60, 4.5),
(26, 'Central Stay', 'Lower Parel', 'Mumbai', 23000, 'Double', 'Unisex', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 0.50, 4.7),
(27, 'WorkHub PG', 'Lower Parel', 'Mumbai', 20000, 'Double', 'Female', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 0.80, 4.5),
(28, 'City Budget PG', 'Kurla', 'Mumbai', 9000, 'Triple', 'Female', 'No', 'Yes', 'No', 'Yes', 'Yes', 0.60, 3.9),
(29, 'Kurla Comfort', 'Kurla', 'Mumbai', 12000, 'Double', 'Unisex', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 0.40, 4.2),
(30, 'Metro Girls PG', 'Kurla', 'Mumbai', 14500, 'Double', 'Female', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 0.30, 4.4);                          
Add PG rental dataset
